# Generated by Django 3.2.5 on 2025-08-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'location', 'start_time', 'end_time')},
        ),
    ]
